### ISSUE TITLE
Recompose fails when combining marks have both anchor and _anchor

### ISSUE THREAD

**Issue by rbmntjs** [jenskutilek/AnchorOverlayTool#3]
When I recompose in a situation where the combining mark has both an anchor and an _anchor (the former for `mkmk` functionality), then the composition places the mark at the anchor, not the _anchor. Does that make sense?

**Comment by jenskutilek** [comment]
Fixed in 105e886656af658e9e03506b297caf34b64ca849. Can you try if it works for you? Sorry it took so long.

**Comment by rbmntjs** [comment]
Fantastic, that works perfectly. Thank you so much!
